### ISSUE TITLE
Texture Coords get warped on non-square brush faces

### ISSUE THREAD

**Issue by snake-biscuits** [MRVN-Radiant/MRVN-Radiant#14]
Texture projection math is hard
Could also be a vertex indexing problem but idk, just gotta:
 - [ ] refactor the math
 - [ ] compile test maps
 - [ ] stare at them

**Comment by F1F7Y** [comment]
Should be fixed on main. ( I'm guessing you're talking about UVs being funky in general, not just on non-square brush faces )
