### ISSUE TITLE
COMPILING.md is out of date

### ISSUE THREAD

**Issue by snake-biscuits** [MRVN-Radiant/MRVN-Radiant#46]
Following the Windows (using Msys/MinGW) guide in COMPILING.md

Need to add `mingw-w64-x86_64-qt5-base` to dependencies
Any dependencies we no longer use should also be removed.

I assume the work has already been done in [`.github/workflows/build.yml`](https://github.com/MRVN-Radiant/MRVN-Radiant/blob/main/.github/workflows/build.yml).
Should only need to change the documentation.

**Comment by F1F7Y** [comment]
Unsure If I'll get to this this weekend, will for sure get to it the next one though

**Comment by F1F7Y** [comment]
Fixed in #47
